Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
   num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Quanto vc calça")
   leia(num)
   Escolha num
      caso 40
           escreva("vc tem um pezao")
      caso 37
           escreva("tamanho de pé considerável")
      caso 35
           escreva("Vc tem um pezinho")
      FimEscolha
Fimalgoritmo